site_name: BEAST.jl
site_author: krcools
site_description: Documentation for BEAST.jl
repo_url: https://github.com/krcools/BEAST.jl

markdown_extensions:
    - mdx_math

extra_javascript:
    - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
    - assets/mathjaxhelper.js

docs_dir: build
pages:
    - Home: index.md
    - Tutorial: tutorial.md
    - Assembly: assemble.md
